/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type MessageType = typeof MessageType[keyof typeof MessageType];


export const MessageType = {
  human: 'human',
  ai: 'ai',
  tool: 'tool',
} as const;
