/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { MessageArgs } from './messageArgs';
import type { MessageType } from './messageType';

export interface Message {
  type: MessageType;
  content: string;
  id?: string | null;
  tool_call_id?: string | null;
  name?: string | null;
  args?: MessageArgs;
  output?: string | null;
}
