/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PostThreadRequestQuery } from './postThreadRequestQuery';

export interface PostThreadRequest {
  query: PostThreadRequestQuery;
}
