/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetMessagesResponse,
  HTTPValidationError,
  PatchThreadRequest,
  PostMessagesRequest,
  PostThreadRequest,
  PostThreadsResponse
} from '.././model';





/**
 * @summary Health Check
 */
export type healthCheckGetResponse200 = {
  data: unknown
  status: 200
}
    
export type healthCheckGetResponseSuccess = (healthCheckGetResponse200) & {
  headers: Headers;
};
;

export type healthCheckGetResponse = (healthCheckGetResponseSuccess)

export const getHealthCheckGetUrl = () => {


  

  return `/`
}

export const healthCheckGet = async ( options?: RequestInit): Promise<healthCheckGetResponse> => {
  
  const res = await fetch(getHealthCheckGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: healthCheckGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthCheckGetResponse
}





export const getHealthCheckGetQueryKey = () => {
    return [
    `/`
    ] as const;
    }

    
export const getHealthCheckGetQueryOptions = <TData = Awaited<ReturnType<typeof healthCheckGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheckGet>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheckGet>>> = ({ signal }) => healthCheckGet({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheckGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthCheckGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheckGet>>>
export type HealthCheckGetQueryError = unknown


export function useHealthCheckGet<TData = Awaited<ReturnType<typeof healthCheckGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheckGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthCheckGet>>,
          TError,
          Awaited<ReturnType<typeof healthCheckGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheckGet<TData = Awaited<ReturnType<typeof healthCheckGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheckGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthCheckGet>>,
          TError,
          Awaited<ReturnType<typeof healthCheckGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheckGet<TData = Awaited<ReturnType<typeof healthCheckGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheckGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health Check
 */

export function useHealthCheckGet<TData = Awaited<ReturnType<typeof healthCheckGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheckGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthCheckGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Threads
 */
export type getThreadsApiThreadsGetResponse200 = {
  data: unknown
  status: 200
}

export type getThreadsApiThreadsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getThreadsApiThreadsGetResponseSuccess = (getThreadsApiThreadsGetResponse200) & {
  headers: Headers;
};
export type getThreadsApiThreadsGetResponseError = (getThreadsApiThreadsGetResponse422) & {
  headers: Headers;
};

export type getThreadsApiThreadsGetResponse = (getThreadsApiThreadsGetResponseSuccess | getThreadsApiThreadsGetResponseError)

export const getGetThreadsApiThreadsGetUrl = () => {


  

  return `/api/threads`
}

export const getThreadsApiThreadsGet = async ( options?: RequestInit): Promise<getThreadsApiThreadsGetResponse> => {
  
  const res = await fetch(getGetThreadsApiThreadsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getThreadsApiThreadsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getThreadsApiThreadsGetResponse
}





export const getGetThreadsApiThreadsGetQueryKey = () => {
    return [
    `/api/threads`
    ] as const;
    }

    
export const getGetThreadsApiThreadsGetQueryOptions = <TData = Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError = HTTPValidationError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetThreadsApiThreadsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getThreadsApiThreadsGet>>> = ({ signal }) => getThreadsApiThreadsGet({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetThreadsApiThreadsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getThreadsApiThreadsGet>>>
export type GetThreadsApiThreadsGetQueryError = HTTPValidationError


export function useGetThreadsApiThreadsGet<TData = Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError = HTTPValidationError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getThreadsApiThreadsGet>>,
          TError,
          Awaited<ReturnType<typeof getThreadsApiThreadsGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetThreadsApiThreadsGet<TData = Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getThreadsApiThreadsGet>>,
          TError,
          Awaited<ReturnType<typeof getThreadsApiThreadsGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetThreadsApiThreadsGet<TData = Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Threads
 */

export function useGetThreadsApiThreadsGet<TData = Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetThreadsApiThreadsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Thread
 */
export type createThreadApiThreadsPostResponse200 = {
  data: PostThreadsResponse
  status: 200
}

export type createThreadApiThreadsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type createThreadApiThreadsPostResponseSuccess = (createThreadApiThreadsPostResponse200) & {
  headers: Headers;
};
export type createThreadApiThreadsPostResponseError = (createThreadApiThreadsPostResponse422) & {
  headers: Headers;
};

export type createThreadApiThreadsPostResponse = (createThreadApiThreadsPostResponseSuccess | createThreadApiThreadsPostResponseError)

export const getCreateThreadApiThreadsPostUrl = () => {


  

  return `/api/threads`
}

export const createThreadApiThreadsPost = async (postThreadRequest: PostThreadRequest, options?: RequestInit): Promise<createThreadApiThreadsPostResponse> => {
  
  const res = await fetch(getCreateThreadApiThreadsPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postThreadRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createThreadApiThreadsPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createThreadApiThreadsPostResponse
}




export const getCreateThreadApiThreadsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createThreadApiThreadsPost>>, TError,{data: PostThreadRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createThreadApiThreadsPost>>, TError,{data: PostThreadRequest}, TContext> => {

const mutationKey = ['createThreadApiThreadsPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createThreadApiThreadsPost>>, {data: PostThreadRequest}> = (props) => {
          const {data} = props ?? {};

          return  createThreadApiThreadsPost(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateThreadApiThreadsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createThreadApiThreadsPost>>>
    export type CreateThreadApiThreadsPostMutationBody = PostThreadRequest
    export type CreateThreadApiThreadsPostMutationError = HTTPValidationError

    /**
 * @summary Create Thread
 */
export const useCreateThreadApiThreadsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createThreadApiThreadsPost>>, TError,{data: PostThreadRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createThreadApiThreadsPost>>,
        TError,
        {data: PostThreadRequest},
        TContext
      > => {
      return useMutation(getCreateThreadApiThreadsPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Rename Thread
 */
export type renameThreadApiThreadsThreadIdPatchResponse200 = {
  data: unknown
  status: 200
}

export type renameThreadApiThreadsThreadIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type renameThreadApiThreadsThreadIdPatchResponseSuccess = (renameThreadApiThreadsThreadIdPatchResponse200) & {
  headers: Headers;
};
export type renameThreadApiThreadsThreadIdPatchResponseError = (renameThreadApiThreadsThreadIdPatchResponse422) & {
  headers: Headers;
};

export type renameThreadApiThreadsThreadIdPatchResponse = (renameThreadApiThreadsThreadIdPatchResponseSuccess | renameThreadApiThreadsThreadIdPatchResponseError)

export const getRenameThreadApiThreadsThreadIdPatchUrl = (threadId: string,) => {


  

  return `/api/threads/${threadId}`
}

export const renameThreadApiThreadsThreadIdPatch = async (threadId: string,
    patchThreadRequest: PatchThreadRequest, options?: RequestInit): Promise<renameThreadApiThreadsThreadIdPatchResponse> => {
  
  const res = await fetch(getRenameThreadApiThreadsThreadIdPatchUrl(threadId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchThreadRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: renameThreadApiThreadsThreadIdPatchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as renameThreadApiThreadsThreadIdPatchResponse
}




export const getRenameThreadApiThreadsThreadIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameThreadApiThreadsThreadIdPatch>>, TError,{threadId: string;data: PatchThreadRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof renameThreadApiThreadsThreadIdPatch>>, TError,{threadId: string;data: PatchThreadRequest}, TContext> => {

const mutationKey = ['renameThreadApiThreadsThreadIdPatch'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof renameThreadApiThreadsThreadIdPatch>>, {threadId: string;data: PatchThreadRequest}> = (props) => {
          const {threadId,data} = props ?? {};

          return  renameThreadApiThreadsThreadIdPatch(threadId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RenameThreadApiThreadsThreadIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof renameThreadApiThreadsThreadIdPatch>>>
    export type RenameThreadApiThreadsThreadIdPatchMutationBody = PatchThreadRequest
    export type RenameThreadApiThreadsThreadIdPatchMutationError = HTTPValidationError

    /**
 * @summary Rename Thread
 */
export const useRenameThreadApiThreadsThreadIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameThreadApiThreadsThreadIdPatch>>, TError,{threadId: string;data: PatchThreadRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof renameThreadApiThreadsThreadIdPatch>>,
        TError,
        {threadId: string;data: PatchThreadRequest},
        TContext
      > => {
      return useMutation(getRenameThreadApiThreadsThreadIdPatchMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Thread
 */
export type deleteThreadApiThreadsThreadIdDeleteResponse200 = {
  data: unknown
  status: 200
}

export type deleteThreadApiThreadsThreadIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type deleteThreadApiThreadsThreadIdDeleteResponseSuccess = (deleteThreadApiThreadsThreadIdDeleteResponse200) & {
  headers: Headers;
};
export type deleteThreadApiThreadsThreadIdDeleteResponseError = (deleteThreadApiThreadsThreadIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteThreadApiThreadsThreadIdDeleteResponse = (deleteThreadApiThreadsThreadIdDeleteResponseSuccess | deleteThreadApiThreadsThreadIdDeleteResponseError)

export const getDeleteThreadApiThreadsThreadIdDeleteUrl = (threadId: string,) => {


  

  return `/api/threads/${threadId}`
}

export const deleteThreadApiThreadsThreadIdDelete = async (threadId: string, options?: RequestInit): Promise<deleteThreadApiThreadsThreadIdDeleteResponse> => {
  
  const res = await fetch(getDeleteThreadApiThreadsThreadIdDeleteUrl(threadId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteThreadApiThreadsThreadIdDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteThreadApiThreadsThreadIdDeleteResponse
}




export const getDeleteThreadApiThreadsThreadIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteThreadApiThreadsThreadIdDelete>>, TError,{threadId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteThreadApiThreadsThreadIdDelete>>, TError,{threadId: string}, TContext> => {

const mutationKey = ['deleteThreadApiThreadsThreadIdDelete'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteThreadApiThreadsThreadIdDelete>>, {threadId: string}> = (props) => {
          const {threadId} = props ?? {};

          return  deleteThreadApiThreadsThreadIdDelete(threadId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteThreadApiThreadsThreadIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteThreadApiThreadsThreadIdDelete>>>
    
    export type DeleteThreadApiThreadsThreadIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Thread
 */
export const useDeleteThreadApiThreadsThreadIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteThreadApiThreadsThreadIdDelete>>, TError,{threadId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteThreadApiThreadsThreadIdDelete>>,
        TError,
        {threadId: string},
        TContext
      > => {
      return useMutation(getDeleteThreadApiThreadsThreadIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Messages
 */
export type getMessagesApiThreadsThreadIdMessagesGetResponse200 = {
  data: GetMessagesResponse
  status: 200
}

export type getMessagesApiThreadsThreadIdMessagesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getMessagesApiThreadsThreadIdMessagesGetResponseSuccess = (getMessagesApiThreadsThreadIdMessagesGetResponse200) & {
  headers: Headers;
};
export type getMessagesApiThreadsThreadIdMessagesGetResponseError = (getMessagesApiThreadsThreadIdMessagesGetResponse422) & {
  headers: Headers;
};

export type getMessagesApiThreadsThreadIdMessagesGetResponse = (getMessagesApiThreadsThreadIdMessagesGetResponseSuccess | getMessagesApiThreadsThreadIdMessagesGetResponseError)

export const getGetMessagesApiThreadsThreadIdMessagesGetUrl = (threadId: string,) => {


  

  return `/api/threads/${threadId}/messages`
}

export const getMessagesApiThreadsThreadIdMessagesGet = async (threadId: string, options?: RequestInit): Promise<getMessagesApiThreadsThreadIdMessagesGetResponse> => {
  
  const res = await fetch(getGetMessagesApiThreadsThreadIdMessagesGetUrl(threadId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMessagesApiThreadsThreadIdMessagesGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMessagesApiThreadsThreadIdMessagesGetResponse
}





export const getGetMessagesApiThreadsThreadIdMessagesGetQueryKey = (threadId: string,) => {
    return [
    `/api/threads/${threadId}/messages`
    ] as const;
    }

    
export const getGetMessagesApiThreadsThreadIdMessagesGetQueryOptions = <TData = Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError = HTTPValidationError>(threadId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMessagesApiThreadsThreadIdMessagesGetQueryKey(threadId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>> = ({ signal }) => getMessagesApiThreadsThreadIdMessagesGet(threadId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(threadId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMessagesApiThreadsThreadIdMessagesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>>
export type GetMessagesApiThreadsThreadIdMessagesGetQueryError = HTTPValidationError


export function useGetMessagesApiThreadsThreadIdMessagesGet<TData = Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError = HTTPValidationError>(
 threadId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>,
          TError,
          Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessagesApiThreadsThreadIdMessagesGet<TData = Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError = HTTPValidationError>(
 threadId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>,
          TError,
          Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessagesApiThreadsThreadIdMessagesGet<TData = Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError = HTTPValidationError>(
 threadId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Messages
 */

export function useGetMessagesApiThreadsThreadIdMessagesGet<TData = Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError = HTTPValidationError>(
 threadId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMessagesApiThreadsThreadIdMessagesGetQueryOptions(threadId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Chat Endpoint
 */
export type chatEndpointApiThreadsThreadIdMessagesPostResponse200 = {
  data: unknown
  status: 200
}

export type chatEndpointApiThreadsThreadIdMessagesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type chatEndpointApiThreadsThreadIdMessagesPostResponseSuccess = (chatEndpointApiThreadsThreadIdMessagesPostResponse200) & {
  headers: Headers;
};
export type chatEndpointApiThreadsThreadIdMessagesPostResponseError = (chatEndpointApiThreadsThreadIdMessagesPostResponse422) & {
  headers: Headers;
};

export type chatEndpointApiThreadsThreadIdMessagesPostResponse = (chatEndpointApiThreadsThreadIdMessagesPostResponseSuccess | chatEndpointApiThreadsThreadIdMessagesPostResponseError)

export const getChatEndpointApiThreadsThreadIdMessagesPostUrl = (threadId: string,) => {


  

  return `/api/threads/${threadId}/messages`
}

export const chatEndpointApiThreadsThreadIdMessagesPost = async (threadId: string,
    postMessagesRequest: PostMessagesRequest, options?: RequestInit): Promise<chatEndpointApiThreadsThreadIdMessagesPostResponse> => {
  
  const res = await fetch(getChatEndpointApiThreadsThreadIdMessagesPostUrl(threadId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postMessagesRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: chatEndpointApiThreadsThreadIdMessagesPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as chatEndpointApiThreadsThreadIdMessagesPostResponse
}




export const getChatEndpointApiThreadsThreadIdMessagesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatEndpointApiThreadsThreadIdMessagesPost>>, TError,{threadId: string;data: PostMessagesRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof chatEndpointApiThreadsThreadIdMessagesPost>>, TError,{threadId: string;data: PostMessagesRequest}, TContext> => {

const mutationKey = ['chatEndpointApiThreadsThreadIdMessagesPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof chatEndpointApiThreadsThreadIdMessagesPost>>, {threadId: string;data: PostMessagesRequest}> = (props) => {
          const {threadId,data} = props ?? {};

          return  chatEndpointApiThreadsThreadIdMessagesPost(threadId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ChatEndpointApiThreadsThreadIdMessagesPostMutationResult = NonNullable<Awaited<ReturnType<typeof chatEndpointApiThreadsThreadIdMessagesPost>>>
    export type ChatEndpointApiThreadsThreadIdMessagesPostMutationBody = PostMessagesRequest
    export type ChatEndpointApiThreadsThreadIdMessagesPostMutationError = HTTPValidationError

    /**
 * @summary Chat Endpoint
 */
export const useChatEndpointApiThreadsThreadIdMessagesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatEndpointApiThreadsThreadIdMessagesPost>>, TError,{threadId: string;data: PostMessagesRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof chatEndpointApiThreadsThreadIdMessagesPost>>,
        TError,
        {threadId: string;data: PostMessagesRequest},
        TContext
      > => {
      return useMutation(getChatEndpointApiThreadsThreadIdMessagesPostMutationOptions(options), queryClient);
    }
    