/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetMessagesResponse,
  GetThreadsResponse,
  HTTPValidationError,
  PostMessagesRequest,
  PostThreadRequest,
  PostThreadsResponse
} from '.././model';





/**
 * @summary Health Check
 */
export type healthCheckHeadResponse200 = {
  data: unknown
  status: 200
}
    
export type healthCheckHeadResponseSuccess = (healthCheckHeadResponse200) & {
  headers: Headers;
};
;

export type healthCheckHeadResponse = (healthCheckHeadResponseSuccess)

export const getHealthCheckHeadUrl = () => {


  

  return `/`
}

export const healthCheckHead = async ( options?: RequestInit): Promise<healthCheckHeadResponse> => {
  
  const res = await fetch(getHealthCheckHeadUrl(),
  {      
    ...options,
    method: 'HEAD'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: healthCheckHeadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthCheckHeadResponse
}




export const getHealthCheckHeadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthCheckHead>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof healthCheckHead>>, TError,void, TContext> => {

const mutationKey = ['healthCheckHead'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof healthCheckHead>>, void> = () => {
          

          return  healthCheckHead(fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type HealthCheckHeadMutationResult = NonNullable<Awaited<ReturnType<typeof healthCheckHead>>>
    
    export type HealthCheckHeadMutationError = unknown

    /**
 * @summary Health Check
 */
export const useHealthCheckHead = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthCheckHead>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof healthCheckHead>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getHealthCheckHeadMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Threads
 */
export type getThreadsApiThreadsGetResponse200 = {
  data: GetThreadsResponse
  status: 200
}

export type getThreadsApiThreadsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getThreadsApiThreadsGetResponseSuccess = (getThreadsApiThreadsGetResponse200) & {
  headers: Headers;
};
export type getThreadsApiThreadsGetResponseError = (getThreadsApiThreadsGetResponse422) & {
  headers: Headers;
};

export type getThreadsApiThreadsGetResponse = (getThreadsApiThreadsGetResponseSuccess | getThreadsApiThreadsGetResponseError)

export const getGetThreadsApiThreadsGetUrl = () => {


  

  return `/api/threads`
}

export const getThreadsApiThreadsGet = async ( options?: RequestInit): Promise<getThreadsApiThreadsGetResponse> => {
  
  const res = await fetch(getGetThreadsApiThreadsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getThreadsApiThreadsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getThreadsApiThreadsGetResponse
}





export const getGetThreadsApiThreadsGetQueryKey = () => {
    return [
    `/api/threads`
    ] as const;
    }

    
export const getGetThreadsApiThreadsGetQueryOptions = <TData = Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError = HTTPValidationError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetThreadsApiThreadsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getThreadsApiThreadsGet>>> = ({ signal }) => getThreadsApiThreadsGet({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetThreadsApiThreadsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getThreadsApiThreadsGet>>>
export type GetThreadsApiThreadsGetQueryError = HTTPValidationError


export function useGetThreadsApiThreadsGet<TData = Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError = HTTPValidationError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getThreadsApiThreadsGet>>,
          TError,
          Awaited<ReturnType<typeof getThreadsApiThreadsGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetThreadsApiThreadsGet<TData = Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getThreadsApiThreadsGet>>,
          TError,
          Awaited<ReturnType<typeof getThreadsApiThreadsGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetThreadsApiThreadsGet<TData = Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Threads
 */

export function useGetThreadsApiThreadsGet<TData = Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadsApiThreadsGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetThreadsApiThreadsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Thread
 */
export type createThreadApiThreadsPostResponse200 = {
  data: PostThreadsResponse
  status: 200
}

export type createThreadApiThreadsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type createThreadApiThreadsPostResponseSuccess = (createThreadApiThreadsPostResponse200) & {
  headers: Headers;
};
export type createThreadApiThreadsPostResponseError = (createThreadApiThreadsPostResponse422) & {
  headers: Headers;
};

export type createThreadApiThreadsPostResponse = (createThreadApiThreadsPostResponseSuccess | createThreadApiThreadsPostResponseError)

export const getCreateThreadApiThreadsPostUrl = () => {


  

  return `/api/threads`
}

export const createThreadApiThreadsPost = async (postThreadRequest: PostThreadRequest, options?: RequestInit): Promise<createThreadApiThreadsPostResponse> => {
  
  const res = await fetch(getCreateThreadApiThreadsPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postThreadRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createThreadApiThreadsPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createThreadApiThreadsPostResponse
}




export const getCreateThreadApiThreadsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createThreadApiThreadsPost>>, TError,{data: PostThreadRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createThreadApiThreadsPost>>, TError,{data: PostThreadRequest}, TContext> => {

const mutationKey = ['createThreadApiThreadsPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createThreadApiThreadsPost>>, {data: PostThreadRequest}> = (props) => {
          const {data} = props ?? {};

          return  createThreadApiThreadsPost(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateThreadApiThreadsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createThreadApiThreadsPost>>>
    export type CreateThreadApiThreadsPostMutationBody = PostThreadRequest
    export type CreateThreadApiThreadsPostMutationError = HTTPValidationError

    /**
 * @summary Create Thread
 */
export const useCreateThreadApiThreadsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createThreadApiThreadsPost>>, TError,{data: PostThreadRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createThreadApiThreadsPost>>,
        TError,
        {data: PostThreadRequest},
        TContext
      > => {
      return useMutation(getCreateThreadApiThreadsPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Update Thread
 */
export type updateThreadApiThreadsThreadIdPutResponse200 = {
  data: unknown
  status: 200
}

export type updateThreadApiThreadsThreadIdPutResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type updateThreadApiThreadsThreadIdPutResponseSuccess = (updateThreadApiThreadsThreadIdPutResponse200) & {
  headers: Headers;
};
export type updateThreadApiThreadsThreadIdPutResponseError = (updateThreadApiThreadsThreadIdPutResponse422) & {
  headers: Headers;
};

export type updateThreadApiThreadsThreadIdPutResponse = (updateThreadApiThreadsThreadIdPutResponseSuccess | updateThreadApiThreadsThreadIdPutResponseError)

export const getUpdateThreadApiThreadsThreadIdPutUrl = (threadId: string,) => {


  

  return `/api/threads/${threadId}`
}

export const updateThreadApiThreadsThreadIdPut = async (threadId: string, options?: RequestInit): Promise<updateThreadApiThreadsThreadIdPutResponse> => {
  
  const res = await fetch(getUpdateThreadApiThreadsThreadIdPutUrl(threadId),
  {      
    ...options,
    method: 'PUT'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateThreadApiThreadsThreadIdPutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateThreadApiThreadsThreadIdPutResponse
}




export const getUpdateThreadApiThreadsThreadIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateThreadApiThreadsThreadIdPut>>, TError,{threadId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateThreadApiThreadsThreadIdPut>>, TError,{threadId: string}, TContext> => {

const mutationKey = ['updateThreadApiThreadsThreadIdPut'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateThreadApiThreadsThreadIdPut>>, {threadId: string}> = (props) => {
          const {threadId} = props ?? {};

          return  updateThreadApiThreadsThreadIdPut(threadId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateThreadApiThreadsThreadIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateThreadApiThreadsThreadIdPut>>>
    
    export type UpdateThreadApiThreadsThreadIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Thread
 */
export const useUpdateThreadApiThreadsThreadIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateThreadApiThreadsThreadIdPut>>, TError,{threadId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateThreadApiThreadsThreadIdPut>>,
        TError,
        {threadId: string},
        TContext
      > => {
      return useMutation(getUpdateThreadApiThreadsThreadIdPutMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Thread
 */
export type deleteThreadApiThreadsThreadIdDeleteResponse200 = {
  data: unknown
  status: 200
}

export type deleteThreadApiThreadsThreadIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type deleteThreadApiThreadsThreadIdDeleteResponseSuccess = (deleteThreadApiThreadsThreadIdDeleteResponse200) & {
  headers: Headers;
};
export type deleteThreadApiThreadsThreadIdDeleteResponseError = (deleteThreadApiThreadsThreadIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteThreadApiThreadsThreadIdDeleteResponse = (deleteThreadApiThreadsThreadIdDeleteResponseSuccess | deleteThreadApiThreadsThreadIdDeleteResponseError)

export const getDeleteThreadApiThreadsThreadIdDeleteUrl = (threadId: string,) => {


  

  return `/api/threads/${threadId}`
}

export const deleteThreadApiThreadsThreadIdDelete = async (threadId: string, options?: RequestInit): Promise<deleteThreadApiThreadsThreadIdDeleteResponse> => {
  
  const res = await fetch(getDeleteThreadApiThreadsThreadIdDeleteUrl(threadId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteThreadApiThreadsThreadIdDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteThreadApiThreadsThreadIdDeleteResponse
}




export const getDeleteThreadApiThreadsThreadIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteThreadApiThreadsThreadIdDelete>>, TError,{threadId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteThreadApiThreadsThreadIdDelete>>, TError,{threadId: string}, TContext> => {

const mutationKey = ['deleteThreadApiThreadsThreadIdDelete'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteThreadApiThreadsThreadIdDelete>>, {threadId: string}> = (props) => {
          const {threadId} = props ?? {};

          return  deleteThreadApiThreadsThreadIdDelete(threadId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteThreadApiThreadsThreadIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteThreadApiThreadsThreadIdDelete>>>
    
    export type DeleteThreadApiThreadsThreadIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Thread
 */
export const useDeleteThreadApiThreadsThreadIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteThreadApiThreadsThreadIdDelete>>, TError,{threadId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteThreadApiThreadsThreadIdDelete>>,
        TError,
        {threadId: string},
        TContext
      > => {
      return useMutation(getDeleteThreadApiThreadsThreadIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Messages
 */
export type getMessagesApiThreadsThreadIdMessagesGetResponse200 = {
  data: GetMessagesResponse
  status: 200
}

export type getMessagesApiThreadsThreadIdMessagesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getMessagesApiThreadsThreadIdMessagesGetResponseSuccess = (getMessagesApiThreadsThreadIdMessagesGetResponse200) & {
  headers: Headers;
};
export type getMessagesApiThreadsThreadIdMessagesGetResponseError = (getMessagesApiThreadsThreadIdMessagesGetResponse422) & {
  headers: Headers;
};

export type getMessagesApiThreadsThreadIdMessagesGetResponse = (getMessagesApiThreadsThreadIdMessagesGetResponseSuccess | getMessagesApiThreadsThreadIdMessagesGetResponseError)

export const getGetMessagesApiThreadsThreadIdMessagesGetUrl = (threadId: string,) => {


  

  return `/api/threads/${threadId}/messages`
}

export const getMessagesApiThreadsThreadIdMessagesGet = async (threadId: string, options?: RequestInit): Promise<getMessagesApiThreadsThreadIdMessagesGetResponse> => {
  
  const res = await fetch(getGetMessagesApiThreadsThreadIdMessagesGetUrl(threadId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMessagesApiThreadsThreadIdMessagesGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMessagesApiThreadsThreadIdMessagesGetResponse
}





export const getGetMessagesApiThreadsThreadIdMessagesGetQueryKey = (threadId: string,) => {
    return [
    `/api/threads/${threadId}/messages`
    ] as const;
    }

    
export const getGetMessagesApiThreadsThreadIdMessagesGetQueryOptions = <TData = Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError = HTTPValidationError>(threadId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMessagesApiThreadsThreadIdMessagesGetQueryKey(threadId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>> = ({ signal }) => getMessagesApiThreadsThreadIdMessagesGet(threadId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(threadId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMessagesApiThreadsThreadIdMessagesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>>
export type GetMessagesApiThreadsThreadIdMessagesGetQueryError = HTTPValidationError


export function useGetMessagesApiThreadsThreadIdMessagesGet<TData = Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError = HTTPValidationError>(
 threadId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>,
          TError,
          Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessagesApiThreadsThreadIdMessagesGet<TData = Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError = HTTPValidationError>(
 threadId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>,
          TError,
          Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessagesApiThreadsThreadIdMessagesGet<TData = Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError = HTTPValidationError>(
 threadId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Messages
 */

export function useGetMessagesApiThreadsThreadIdMessagesGet<TData = Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError = HTTPValidationError>(
 threadId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesApiThreadsThreadIdMessagesGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMessagesApiThreadsThreadIdMessagesGetQueryOptions(threadId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Invoke
 */
export type invokeApiThreadsThreadIdMessagesPostResponse200 = {
  data: unknown
  status: 200
}

export type invokeApiThreadsThreadIdMessagesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type invokeApiThreadsThreadIdMessagesPostResponseSuccess = (invokeApiThreadsThreadIdMessagesPostResponse200) & {
  headers: Headers;
};
export type invokeApiThreadsThreadIdMessagesPostResponseError = (invokeApiThreadsThreadIdMessagesPostResponse422) & {
  headers: Headers;
};

export type invokeApiThreadsThreadIdMessagesPostResponse = (invokeApiThreadsThreadIdMessagesPostResponseSuccess | invokeApiThreadsThreadIdMessagesPostResponseError)

export const getInvokeApiThreadsThreadIdMessagesPostUrl = (threadId: string,) => {


  

  return `/api/threads/${threadId}/messages`
}

export const invokeApiThreadsThreadIdMessagesPost = async (threadId: string,
    postMessagesRequest: PostMessagesRequest, options?: RequestInit): Promise<invokeApiThreadsThreadIdMessagesPostResponse> => {
  
  const res = await fetch(getInvokeApiThreadsThreadIdMessagesPostUrl(threadId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postMessagesRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: invokeApiThreadsThreadIdMessagesPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as invokeApiThreadsThreadIdMessagesPostResponse
}




export const getInvokeApiThreadsThreadIdMessagesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invokeApiThreadsThreadIdMessagesPost>>, TError,{threadId: string;data: PostMessagesRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof invokeApiThreadsThreadIdMessagesPost>>, TError,{threadId: string;data: PostMessagesRequest}, TContext> => {

const mutationKey = ['invokeApiThreadsThreadIdMessagesPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof invokeApiThreadsThreadIdMessagesPost>>, {threadId: string;data: PostMessagesRequest}> = (props) => {
          const {threadId,data} = props ?? {};

          return  invokeApiThreadsThreadIdMessagesPost(threadId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type InvokeApiThreadsThreadIdMessagesPostMutationResult = NonNullable<Awaited<ReturnType<typeof invokeApiThreadsThreadIdMessagesPost>>>
    export type InvokeApiThreadsThreadIdMessagesPostMutationBody = PostMessagesRequest
    export type InvokeApiThreadsThreadIdMessagesPostMutationError = HTTPValidationError

    /**
 * @summary Invoke
 */
export const useInvokeApiThreadsThreadIdMessagesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invokeApiThreadsThreadIdMessagesPost>>, TError,{threadId: string;data: PostMessagesRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof invokeApiThreadsThreadIdMessagesPost>>,
        TError,
        {threadId: string;data: PostMessagesRequest},
        TContext
      > => {
      return useMutation(getInvokeApiThreadsThreadIdMessagesPostMutationOptions(options), queryClient);
    }
    